your_number = int(input("please enter your number"))
print(your_number * 1)
print(your_number * 2)
print(your_number * 3)
print(your_number * 4)
print(your_number * 5)
print(your_number * 6)
print(your_number * 7)
print(your_number * 8)
print(your_number * 9)
print(your_number * 10)
